{% set version = "1.7" %}
package:
  name: bash-completion-conda
  version: "{{ version }}"

source:
  git_rev: "{{ version }}"
  git_url: https://github.com/antonioshadji/bash-completion-conda

build:
  number: 2

requirements:
  build:
    - bash-completion
  run:
    - bash-completion

test:
    source_files:
      - conda
    commands:
      # Ensure the library loads without error
      - bash -e conda

about:
  home: https://github.com/antonioshadji/bash-completion-conda
  license: GPL3
  license_file: LICENSE
  summary: "Bash completion for the conda commmand."

extra:
  recipe-maintainers:
    - antonioshadji
    - tartansandal
    - matthiasdiener
