{% set version = "1.1" %}
package:
  name: conda-bash-completion
  version: "{{ version }}"

source:
  git_rev: "v{{ version }}"
  git_url: https://github.com/tartansandal/conda-bash-completion

build:
  number: 2

requirements:
  build:
    - bash-completion
  run:
    - bash-completion

# FIXME requires an active environment to load
# test:
#     source_files:
#       - conda
#     commands:
#       # Ensure the library loads without error
#       - bash -vxe conda

about:
  home: https://github.com/tartansandal/conda-bash-completion
  license: GPL3
  license_file: LICENSE
  summary: "Bash completion for the conda commmand."

# vim:set ts=8 sw=2 sts=2 tw=78 et:
